In [1]:
import pandas as pd

In [6]:
df = pd.read_csv('../raw_data/nasdaq_stocks/1/aacg.us.txt')

# Basic information

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3165 entries, 0 to 3164
Data columns (total 10 columns):
<TICKER>     3165 non-null object
<PER>        3165 non-null object
<DATE>       3165 non-null int64
<TIME>       3165 non-null int64
<OPEN>       3165 non-null float64
<HIGH>       3165 non-null float64
<LOW>        3165 non-null float64
<CLOSE>      3165 non-null float64
<VOL>        3165 non-null int64
<OPENINT>    3165 non-null int64
dtypes: float64(4), int64(4), object(2)
memory usage: 247.3+ KB

In [8]:
df.describe()

,<DATE>,<TIME>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<VOL>,<OPENINT>
count,3.165000e+03,3165.0,3165.000000,3165.000000,3165.000000,3165.000000,3.165000e+03,3165.0
mean,2.014168e+07,0.0,0.659672,0.683626,0.639412,0.659417,2.513775e+05,0.0
std,3.778792e+04,0.0,0.455787,0.485600,0.435878,0.456786,1.500811e+06,0.0
min,2.008013e+07,0.0,0.214390,0.224500,0.195320,0.217030,0.000000e+00,0.0
25%,2.011042e+07,0.0,0.375280,0.384860,0.365100,0.375410,2.591900e+04,0.0
50%,2.014091e+07,0.0,0.492320,0.503600,0.480470,0.490480,7.363100e+04,0.0
75%,2.017111e+07,0.0,0.796200,0.815600,0.776800,0.796700,1.935920e+05,0.0
max,2.021012e+07,0.0,3.000000,4.500000,2.850000,3.850000,5.316937e+07,0.0

In [15]:
df.head()

,<TICKER>,<PER>,<DATE>,<TIME>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<VOL>,<OPENINT>
0,AACG.US,D,20080128,0,0.7380,0.7380,0.7380,0.7380,0,0
1,AACG.US,D,20080129,0,0.7380,0.7760,0.6657,0.6797,19169939,0
2,AACG.US,D,20080130,0,0.6797,0.7108,0.6448,0.6603,2818723,0
3,AACG.US,D,20080131,0,0.6595,0.8001,0.6595,0.7418,2345961,0
4,AACG.US,D,20080201,0,0.7714,0.7721,0.7380,0.7387,361853,0

# Date to datetime object

In [10]:
df['<TICKER>'].nunique()

1

In [11]:
df['<PER>'].nunique()

1

In [12]:
df['<TIME>'].nunique()

1

In [13]:
df['<OPENINT>'].nunique()

1

In [32]:
pd.to_datetime(df["<DATE>"], format='%Y%m%d', errors='ignore')

0      2008-01-28
1      2008-01-29
2      2008-01-30
3      2008-01-31
4      2008-02-01
5      2008-02-04
6      2008-02-05
7      2008-02-06
8      2008-02-07
9      2008-02-08
10     2008-02-11
11     2008-02-12
12     2008-02-13
13     2008-02-14
14     2008-02-15
15     2008-02-19
16     2008-02-20
17     2008-02-21
18     2008-02-22
19     2008-02-25
20     2008-02-26
21     2008-02-27
22     2008-02-28
23     2008-02-29
24     2008-03-03
25     2008-03-04
26     2008-03-05
27     2008-03-06
28     2008-03-07
29     2008-03-10
          ...
3135   2020-12-10
3136   2020-12-11
3137   2020-12-14
3138   2020-12-15
3139   2020-12-16
3140   2020-12-17
3141   2020-12-18
3142   2020-12-21
3143   2020-12-22
3144   2020-12-23
3145   2020-12-24
3146   2020-12-28
3147   2020-12-29
3148   2020-12-30
3149   2020-12-31
3150   2021-01-04
3151   2021-01-05
3152   2021-01-06
3153   2021-01-07
3154   2021-01-08
3155   2021-01-11
3156   2021-01-12
3157   2021-01-13
3158   2021-01-14
3159   2021-01-15
3160   2021-01-19
3161   2021-01-20
3162   2021-01-21
3163   2021-01-22
3164   2021-01-25
Name: <DATE>, Length: 3165, dtype: datetime64[ns]

In [37]:
def to_date(df, date_colum): #Use directly the right column as arg?
    dated_col = pd.to_datetime(df[date_colum], format='%Y%m%d', errors='ignore')
    return dated_col

In [38]:
to_date(df, "<DATE>")

0      2008-01-28
1      2008-01-29
2      2008-01-30
3      2008-01-31
4      2008-02-01
5      2008-02-04
6      2008-02-05
7      2008-02-06
8      2008-02-07
9      2008-02-08
10     2008-02-11
11     2008-02-12
12     2008-02-13
13     2008-02-14
14     2008-02-15
15     2008-02-19
16     2008-02-20
17     2008-02-21
18     2008-02-22
19     2008-02-25
20     2008-02-26
21     2008-02-27
22     2008-02-28
23     2008-02-29
24     2008-03-03
25     2008-03-04
26     2008-03-05
27     2008-03-06
28     2008-03-07
29     2008-03-10
          ...
3135   2020-12-10
3136   2020-12-11
3137   2020-12-14
3138   2020-12-15
3139   2020-12-16
3140   2020-12-17
3141   2020-12-18
3142   2020-12-21
3143   2020-12-22
3144   2020-12-23
3145   2020-12-24
3146   2020-12-28
3147   2020-12-29
3148   2020-12-30
3149   2020-12-31
3150   2021-01-04
3151   2021-01-05
3152   2021-01-06
3153   2021-01-07
3154   2021-01-08
3155   2021-01-11
3156   2021-01-12
3157   2021-01-13
3158   2021-01-14
3159   2021-01-15
3160   2021-01-19
3161   2021-01-20
3162   2021-01-21
3163   2021-01-22
3164   2021-01-25
Name: <DATE>, Length: 3165, dtype: datetime64[ns]

# Cleaning columns names

In [40]:
list(df)

['<TICKER>',
 '<PER>',
 '<DATE>',
 '<TIME>',
 '<OPEN>',
 '<HIGH>',
 '<LOW>',
 '<CLOSE>',
 '<VOL>',
 '<OPENINT>']

In [62]:
def proper_name(col):
    col = col.replace('>','')
    col = col.replace('<','')
    col = col.lower()
    return col

def proper_col(df):
    proper_df = pd.DataFrame()
    for col in list(df):
        proper_col = proper_name(col)
        proper_df[proper_col] = df[col]
    return proper_df

In [50]:
proper_name(list(df)[0])

'ticker'

In [63]:
proper_col(df)

,ticker,per,date,time,open,high,low,close,vol,openint
0,AACG.US,D,20080128,0,0.7380,0.7380,0.7380,0.7380,0,0
1,AACG.US,D,20080129,0,0.7380,0.7760,0.6657,0.6797,19169939,0
2,AACG.US,D,20080130,0,0.6797,0.7108,0.6448,0.6603,2818723,0
3,AACG.US,D,20080131,0,0.6595,0.8001,0.6595,0.7418,2345961,0
4,AACG.US,D,20080201,0,0.7714,0.7721,0.7380,0.7387,361853,0
5,AACG.US,D,20080204,0,0.7380,0.7543,0.7380,0.7380,105999,0
6,AACG.US,D,20080205,0,0.7380,0.7380,0.7014,0.7077,379083,0
7,AACG.US,D,20080206,0,0.6991,0.7325,0.6735,0.6991,205548,0
8,AACG.US,D,20080207,0,0.6991,0.7380,0.6991,0.7302,76972,0
9,AACG.US,D,20080208,0,0.7084,0.7217,0.6991,0.6999,100707,0
10,AACG.US,D,20080211,0,0.7030,0.7123,0.6991,0.7022,44081,0
11,AACG.US,D,20080212,0,0.7030,0.7123,0.6991,0.7069,371187,0
12,AACG.US,D,20080213,0,0.6999,0.7030,0.6991,0.6999,169615,0
13,AACG.US,D,20080214,0,0.7061,0.7061,0.6991,0.7038,167673,0
14,AACG.US,D,20080215,0,0.6999,0.7046,0.6991,0.6991,127857,0
15,AACG.US,D,20080219,0,0.7147,0.7185,0.7069,0.7147,39769,0
16,AACG.US,D,20080220,0,0.7147,0.7465,0.7147,0.7465,294859,0
17,AACG.US,D,20080221,0,0.7403,0.8001,0.7403,0.7690,1112319,0
18,AACG.US,D,20080222,0,0.7550,0.7550,0.7473,0.7473,40581,0
19,AACG.US,D,20080225,0,0.7418,0.7418,0.7224,0.7364,84607,0
20,AACG.US,D,20080226,0,0.7380,0.7504,0.7380,0.7426,98476,0
21,AACG.US,D,20080227,0,0.7473,0.7550,0.7387,0.7387,21887,0
22,AACG.US,D,20080228,0,0.7380,0.7690,0.7240,0.7496,88648,0
23,AACG.US,D,20080229,0,0.7411,0.8079,0.7411,0.8001,155353,0
24,AACG.US,D,20080303,0,0.7838,0.8273,0.7838,0.8048,159348,0
25,AACG.US,D,20080304,0,0.7853,0.7962,0.7815,0.7923,45752,0
26,AACG.US,D,20080305,0,0.7853,0.8149,0.7807,0.7923,69440,0
27,AACG.US,D,20080306,0,0.7962,0.8110,0.7923,0.7923,30893,0
28,AACG.US,D,20080307,0,0.7923,0.8444,0.7923,0.8421,131955,0
29,AACG.US,D,20080310,0,0.8141,0.8809,0.8125,0.8809,170296,0
...,...,...,...,...,...,...,...,...,...,...
3135,AACG.US,D,20201210,0,1.1500,1.1900,1.1500,1.1781,4644,0
3136,AACG.US,D,20201211,0,1.1600,1.1900,1.1600,1.1602,13216,0
3137,AACG.US,D,20201214,0,1.1700,1.2100,1.1600,1.1700,21153,0
3138,AACG.US,D,20201215,0,1.1800,1.2000,1.1600,1.2000,6063,0
3139,AACG.US,D,20201216,0,1.1600,1.2001,1.1600,1.2000,44379,0
3140,AACG.US,D,20201217,0,1.2000,1.2000,1.1600,1.1800,5972,0
3141,AACG.US,D,20201218,0,1.1600,1.2002,1.1600,1.2002,9939,0
3142,AACG.US,D,20201221,0,1.1800,1.2000,1.1800,1.2000,12050,0
3143,AACG.US,D,20201222,0,1.2000,1.2300,1.1601,1.1800,12470,0
3144,AACG.US,D,20201223,0,1.2100,1.3000,1.1800,1.2800,78500,0
3145,AACG.US,D,20201224,0,1.2700,1.2799,1.2000,1.2799,49926,0
3146,AACG.US,D,20201228,0,1.2800,1.2800,1.2000,1.2100,49685,0
3147,AACG.US,D,20201229,0,1.1900,1.2300,1.1700,1.1900,139609,0
3148,AACG.US,D,20201230,0,1.1700,1.2100,1.1600,1.1900,21848,0
3149,AACG.US,D,20201231,0,1.2000,1.2100,1.1800,1.1900,32248,0
3150,AACG.US,D,20210104,0,1.1700,1.2200,1.1700,1.1800,17972,0
3151,AACG.US,D,20210105,0,1.2000,1.2735,1.1901,1.2300,21266,0
3152,AACG.US,D,20210106,0,1.2300,1.3000,1.2152,1.2200,41438,0
3153,AACG.US,D,20210107,0,1.3000,1.3000,1.2300,1.2686,20353,0
3154,AACG.US,D,20210108,0,1.2700,1.2838,1.2200,1.2410,18579,0
3155,AACG.US,D,20210111,0,1.2700,1.2999,1.2582,1.2600,28256,0
3156,AACG.US,D,20210112,0,1.2500,1.2601,1.2000,1.2480,63610,0
3157,AACG.US,D,20210113,0,1.2101,1.2600,1.2100,1.2100,31571,0
3158,AACG.US,D,20210114,0,1.2300,1.3000,1.2200,1.2600,43054,0
3159,AACG.US,D,20210115,0,1.2500,1.4600,1.2400,1.2600,109213,0
3160,AACG.US,D,20210119,0,1.3000,1.3940,1.2700,1.3038,63308,0
3161,AACG.US,D,20210120,0,1.3100,1.5100,1.3000,1.3800,206115,0
3162,AACG.US,D,20210121,0,1.4100,1.4200,1.3503,1.4000,45028,0
3163,AACG.US,D,20210122,0,1.4800,1.4899,1.3000,1.3500,80833,0
3164,AACG.US,D,20210125,0,1.4400,1.4600,1.3320,1.3882,32156,0